### ISSUE TITLE
How to describe the provenance of activity classes and activity subclasses , and which PROV property?

### ISSUE THREAD

**Issue by hby10001111** [trungdong/prov#128]
Hi，@satra, @trungdong, 
Sorry to disturb you, I need to ask you a small question .

Entity classes and entity exceptions are described, as follows:

d1.entity("ex:Item"）
d1.entity("ex:RevisionItem"）
d1.specializationOf('ex:RevisionItem_1', 'ex:RevisionItem')

How to describe the provenance of activity classes and individual activities, and which PROV property?
d1.activity('ex:changeRevision') [ this is a class ]
d1.activity('ex:changeRevision_1') [ this is a instance]

In Python's PROV 1.5, how do you introduce attributes (RDFS: subClassOf) to describe activity classes and activity instances

**Comment by hby10001111** [comment]
@satra， I am really excited to see your reply. Thank you very much for your patience.
I am a beginner of provenance, and am working on the description of provenance information using Python's PROV.

“myActivityClass  rdfs:subClassOf  prov:Activity” .
This is a simple and effective method, but it is in Turtle format, and the program defaults to provn, so I try to describe activity classes and activity subclasses as comments  and I found that both entities and agents can be annotated, as shown below：

agent(ex:Bob, [prov:type="Person", ex:givenName="Bob"])
entity(ex:RevisionItem_172, [prov:generatedAtTime="2016-12-01T07:57:00"])
The statement is runnable and the output is in provn format.

But activities cannot add similar comments, as shown below,
d1.activity("ex:Revision")  
d1.activity("ex:addRevision",{"rdfs:superClassOf":"ex:Revision"})   <2>
I wanted to annotate the relationship between activity classes and activity subclasses, As shown in example  <2>，but found it not feasible.

**Comment by satra** [comment]
@hby10001111 - indeed to use provn, you will have to extend the PROV model itself with your requirements. you cannot use the prov library to do extensions of the model. the library is restricted to the PROV data model.

**Comment by hby10001111** [comment]
@satra，Thank you very much for your reply. I will continue to explore Provenance and thank you very much for helping beginners.

**Comment by stain** [comment]
I'm a bit confused when you say an activity is a class.

Is this something like trying to do `specializationOf` with activities instead of entities?

```
d1.activity("ex:Revision")
d1.activity("ex:addRevision",{"rdfs:superClassOf":"ex:Revision"}) <2>
```
so you  ex:Revision are all kinds of revision activities? I don't see how this makes sense to be a PROV Activity - does it last from start of universe to the end of universe?   

(It might make sense for some group actions, like `WomenVotingRightsUK` movement as an activity starting in 1872 ending in 1928, and individual people having "subactivities" taking part of that for smaller durations).

I would advise against having an instance be also a class, that is generally considered bad semantic design as you end up with meta-classes etc and unclear implications.

If you just want to categorize the `ex:addRevision` activity as a kind of Revision-like activity you just need `prov:type`:

```
d1.activity("ex:addRevision",{"prov:type":"ex:Revision"}) <2>
```

This is easy with prov.py:

```python
EX = Namespace("ex", 'http://example.com/revision-ontology#')
document.activity(someId,
            None, None,
            ["prov:type": EX["Revision"],
             "prov:label": "Adding 5+2"])
```

Obviously you would then need to declare what `ex:Revision` class is - but the PROV file is not the right place for that, that should be on http://example.com/revision-ontology#Revision (with your own domain name)

As @satra points out trying to declare non-PROV items like an ontology class in prov.py will probably not be that easy. But you can refer to it using a Namespace reference as above.

Note that you can declare `prov:type` multiple types, which can be a lazy way to declare you are also an instance of a superclass.

## Sub-activities

Below I'll explore sub-activities, like "cooking potatoes" activity involves "filling pot", "peeling potatoes" etc. activities.

If the outer activity is active, like in a workflow, script or program; then you can consider it also as a PROV **Agent**, which then can be said to start the inner activities with `wasStartedBy`

See how we do it in CWLProv:
https://github.com/common-workflow-language/cwlprov/blob/master/prov.md#nested-workflows

[Formally](https://www.w3.org/TR/2013/REC-prov-dm-20130430/Overview.html#term-Start) this approach says the new activity was started by a (here undeclared) _trigger_ Entity produced by the outer activity, typically some kind of signal, request or letter.
