### ISSUE TITLE
TypeError while retrieving ProvDocuments from ProvStore using Py3

### ISSUE THREAD

**Issue by BoJanisch** [trungdong/prov#67]
Hello,

I tried out the Tutorial given at http://nbviewer.ipython.org/github/trungdong/notebooks/blob/master/PROV%20Tutorial.ipynb, everything very nice explained. But I always got exceptions when trying to retrieve ProvDocuments from ProvStore looking like this:

TypeError: initial_value must be str or None, not bytes

This exception was raised by the deserializer from model.py because the content it tried to parse were bytes. I found the origin of the problem in the request call at line 106 r= self._request(...), in api.py from provstore-api module, which returns the content as bytes and that raised the error from the io.StringIO function in the deserializer which accepts only unicode. I simply decoded the content as UTF-8, right before the deserializer is called from the api and everything worked again. I don't know what is responsible for this incompatibility, maybe Windows 7 which I'm using? Anyway please check the compatibility of these modules again.

Best wishes
Bojan

**Comment by trungdong** [comment]
Hello @BoJanisch,

Thank you for reporting this. It was caused by @millar's provstore-api package passing `bytes` objects to the prov package's deserialisers, which wasn't previously supported.

I have now added the support for deserialising Python 3's `bytes` objects in the above commit.

@millar, in the provestore-api package, during deserialising of the content from a request `r`, if you could pass `r.text`, which will be correctly decoded by the requests package, instead of `r.content`, the package will handle strings using codecs other than UTF-8 better, I think. Cheers.
